name: ztdl
channels:
- defaults
dependencies:
- python=3.7.*
- bz2file==0.98
- cython==0.29.*
- pip==21.0.*
- numpy==1.19.*
- jupyter==1.0.*
- matplotlib==3.3.*
- setuptools==52.0.*
- scikit-learn==0.24.*
- scipy==1.6.*
- pandas==1.2.*
- pillow==8.2.*
- seaborn==0.11.*
- pytest==6.2.*
- twisted==21.2.*
- pip:
  - tensorflow==2.5.*
